language:
  - c

before_install:
  - pip install --user cpp-coveralls

addons:
    sonarcloud:
        organization: "kulakovalexey"
    token: travis encrypt 3cd9b4557be6bbc45d2d9bcf7543c2ee6601cd4d

script:
  - qmake
  - make
  - ./tests/tests

after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*" -E ".*main.c.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
